### ISSUE TITLE
Add CTS logo

### ISSUE THREAD

**Issue by haarli** [MPDL/edmond-static-sites#2]
Add CoreTrustSeal logo to the footer with the text "Certified by:" above.
Logos can be found here: https://bit.ly/3fTuAKs

The logo should link to https://amt.coretrustseal.org/certificates/

**Comment by vilaMMXXIII** [comment]
CTS Logo is Live. "Certified by:" text comes as soon as possible.

**Comment by vilaMMXXIII** [comment]
List of tasks to do: 

- Dataverse footer join to content body.
- CTS Logo and equal separation between Logos along the MPDL Footer.

**Comment by vilarodr** [comment]
On Live
